### ISSUE TITLE
Training recipe

### ISSUE THREAD

**Issue by avi33** [quickvc/QuickVoice-Conversion#16]
In section 2.3.2 in paper, you have mentioned that the input in speaker encoder varies between training stages. Can you please point ib code where it takes place?

Do yiu train end to end or given trained generator?
Thanks in advance

**Comment by guoyingying432** [comment]
Please refer  to this:
     https://github.com/quickvc/QuickVC-VoiceConversion/issues/10

**Comment by guoyingying432** [comment]
the model is trained end to end

**Comment by avi33** [comment]
Thank you for your quick response.
