### ISSUE TITLE
48Khz Conversion

### ISSUE THREAD

**Issue by MaN0bhiR** [quickvc/QuickVoice-Conversion#17]
Hey , great work and thanks for making it available to all of us. I am trying to make this work for 48Khz conversion. I am training on same VCTK-Dataset. I've gone through [48Khz](https://github.com/OlaWod/FreeVC/issues/63) issue in FreeVC and make all changes that are mentioned there. I've also changed mel_spectrogram_torch settings train.py file as mentioned in the 48Khz issue in FreeVC. However I am getting following error when I start training.

`RuntimeError: The expanded size of the tensor (65) must match the existing size (0) at non-singleton dimension 1.  Target sizes: [641, 65].  Tensor sizes: [641, 0]`

Its coming from this line `spec_padded, ids_slice = commons.rand_spec_segments(spec_padded, spec_lengths, spec_seglen)` in data_utils_new_new.py

I've been stuck here for past few weeks. Really appreciate any help you can provide.

**Comment by ConsistencyVC** [comment]
Actually I met the same problem....maybe you can refer to this [issue](https://github.com/OlaWod/FreeVC/issues/57).
This problem is because the spec is the old spec(16khz,320hop). But we start from new spec.

**Comment by MaN0bhiR** [comment]
Alright! Thanks.
