### ISSUE TITLE
Training time

### ISSUE THREAD

**Issue by fmac2000** [quickvc/QuickVoice-Conversion#6]
Hi Authors,

Fantastic work, congratulations on being accepted in the conference!
I'm reading through the paper on the training specifications, may I ask how long it took to train the 600K steps? I'm looking forward to training my own checkpoint.

Thanks for opensourcing, really amazing work!

**Comment by quickvc** [comment]
According to #https://github.com/MasayaKawamura/MB-iSTFT-VITS/issues/4, it is a very long time. For me, it takes me about one to two weeks.
